name: 'Execução Agendada'

on:
  schedule:
    - cron: '48 16 * * *'

jobs:
  e2e-tests:
    runs-on: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v4

      # Definir o timezone para o Brasil (America/Sao_Paulo)
      - name: Definindo Timezone para o Brasil
        run: |
          sudo timedatectl set-timezone America/Sao_Paulo
          date  # Exibe a data e horário atuais com o timezone configurado

      - name: Instalando yarn
        run: npm install -g yarn

      - name: Instalando dependencias
        run: yarn

      - name: Instalando playwright
        run: yarn playwright install

      - name: Testes E2E (end-to-end)
        run: yarn run e2e

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report
