


name: 'Execução Agendada'

on:
  schedule:
        - cron: '* * * * *'

jobs:
    e2e-tests:
        runs-on: ['ubuntu-latest']
        
        steps:

        - uses: actions/checkout@v4

        #- uses: action/setup-node@v4

        - name: Instalando yarn
          run:  npm install -g yarn

        - name: Instalando dependencias
          run: yarn

        - name: Instalando playwright
          run: yarn playwright install

        - name: Testes E2E (end-to-end)
          run: yarn  run e2e
                    
        - uses: actions/upload-artifact@v4
          if: ${{ !cancelled() }}
          with:   
            name: relatorio-de-testes
            path: ./playwright-report
