name: 'Execução integrado'

on:
  workflow_dispatch:

jobs:
  inaoect:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: intalando Yarn
        run: npm install -g yarn

      - name: Instalando dependencias
        run: yarn

      - name: instalando dependencias
        run: yarn lint

  unit: 

    runs-on: ['ubuntu-latest']
    
    steps:
      - uses: action/setup-node@v4

      - name: intalando Yarn
        run: npm install -g yarn

      - name: Instalando dependencias
        run: yarn

      - name: Testes de unidade
        run: yarn run test

  e2e-tests:
    runs-on: ['ubuntu-latest']

    steps:
      - uses: actions/checkout@v4

      #- uses: action/setup-node@v4

      - name: Instalando yarn
        run: npm install -g yarn

      - name: Instalando dependencias
        run: yarn

      - name: Instalando playwright
        run: yarn playwright install

      - name: Testes E2E (end-to-end)
        run: yarn  run e2e
        env:
          URL: 'http://localhost:3000'

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-de-testes
          path: ./playwright-report
